segregar migrate mysql e mongo
rrafaelc/Elderly-Fall-Sensor-System-Backend pull request #11
Opened 2024-10-20 21:48 UTC by Triliam

2024-10-20 22:21 UTC, rafaelhgreco approved these changes
OK

2024-10-20 22:25 UTC, rrafaelc requested changes
@Triliam  Atualiza o .env.example com as novas variaveis de ambiente pfv, procurei aqui e não tem lá

![image](https://github.com/user-attachments/assets/17a5f906-e31c-42be-a6fc-40ff07c5b06b)

2024-10-20 22:27 UTC, rrafaelc commented
@Triliam Atualiza tbm todo o .env.example igual ao .env, sem as chaves secretas

2024-10-24 13:56 UTC, rafaelhgreco approved these changes

2024-10-26 13:49 UTC, rafaelhgreco approved these changes

2024-10-26 15:23 UTC, rrafaelc requested changes

2024-10-26 15:23 UTC, rrafaelc commented on .env.example
O .env que voce me passou tem chaves faltando no .env.example, como o JWT_SECRET, sugestao pra colocar no .env.example: 

```APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=fall_detection
DB_USERNAME=root
DB_PASSWORD=12345

MONGO_DB_CONNECTION=mongodb
MONGO_DB_URI=
MONGO_DB_DATABASE=elderly_mongodb


SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

JWT_TTL=42000

JWT_SECRET=

JWT_ALGO=HS256
```

2024-10-26 15:48 UTC, Triliam commented on .env.example
Verdade, não copiei as linhas adicionadas do JWT. Vou fazer agora, dai deixo em branco as informações do mysql, certo?

2024-10-26 17:43 UTC, rrafaelc approved these changes

2024-10-26 18:58 UTC, merged